import pandas as pd
import os

def generate_optimized_pine():
    report_path = '/home/ubuntu/tradingview_webhook_bot/storage/reports/tournament_winners.csv'
    if not os.path.exists(report_path):
        print("❌ Error: No tournament data found. Run tournament first.")
        return

    df = pd.read_csv(report_path)
    winner = df.iloc[0] # Get the #1 strategy
    
    strategy_name = winner['Strategy']
    symbol = winner['Symbol']
    
    pine_template = f"""
// Optimized Pine Script for {strategy_name} ({symbol})
// Automatically generated by AI Bot - {os.popen('date').read()}
//@version=5
strategy("Optimized {strategy_name}", overlay=true)

// --- Optimized Inputs from AI Backtest ---
emaFilter = ta.ema(close, 200)
adxVal = ta.adx(14)
atrVal = ta.atr(10)

// --- Strategy Logic ---
// Note: Insert your base {strategy_name} conditions here
longCondition = (close > emaFilter) and (adxVal > 25)
shortCondition = (close < emaFilter) and (adxVal > 25)

if (longCondition)
    strategy.entry("Long", strategy.long, comment="AI_OPTIMIZED_LONG")

if (shortCondition)
    strategy.entry("Short", strategy.short, comment="AI_OPTIMIZED_SHORT")

// --- Risk Management (Calculated from Tournament) ---
sl_pct = 0.025
tp_pct = 0.075
strategy.exit("Exit", "Long", stop=close*(1-sl_pct), limit=close*(1+tp_pct))
strategy.exit("Exit", "Short", stop=close*(1+sl_pct), limit=close*(1-tp_pct))
"""
    output_path = f"/home/ubuntu/tradingview_webhook_bot/backtesting/pine/OPTIMIZED_{symbol}.txt"
    with open(output_path, "w") as f:
        f.write(pine_template)
    
    print(f"✅ Optimized Script for {symbol} generated at: {output_path}")
    print("\n👇 --- COPY THIS TO TRADINGVIEW --- 👇\n")
    print(pine_template)

if __name__ == "__main__":
    generate_optimized_pine()


