# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Configuration settings loader for trading bot.

This module loads and validates all required environment variables at startup.
Fails fast if required configuration is missing.
"""

import logging
import os
from pathlib import Path
from typing import Optional

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)


class Settings(BaseSettings):
    """
    Application settings loaded from environment variables.

    All secrets (WEBHOOK_SECRET, TELEGRAM_TOKEN) must be provided via
    environment variables and are never logged or exposed in error messages.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )

    # Required: Webhook Configuration
    webhook_secret: str = Field(
        ...,
        alias="WEBHOOK_SECRET",
        description="Secret for validating TradingView webhook requests",
    )

    queue_path: Path = Field(
        default=Path("./tradingview_signals_queue.jsonl"),
        alias="QUEUE_PATH",
        description="Path to JSONL queue file",
    )

    offset_path: Path = Field(
        default=Path("./offset_checkpoint.json"),
        alias="OFFSET_PATH",
        description="Path to offset checkpoint file",
    )

    idempotency_db_path: Path = Field(
        default=Path("./idempotency_store.db"),
        alias="IDEMPOTENCY_DB_PATH",
        description="Path to SQLite idempotency database",
    )

    # Required: Alerting Configuration
    telegram_token: str = Field(
        ...,
        alias="TELEGRAM_TOKEN",
        description="Telegram bot token for sending alerts",
    )

    telegram_chat_id: str = Field(
        ...,
        alias="TELEGRAM_CHAT_ID",
        description="Telegram chat ID for receiving alerts",
    )

    # Optional: Event Log
    event_log_path: Path = Field(
        default=Path("./trading_events.jsonl"),
        alias="EVENT_LOG_PATH",
        description="Path to structured event log file",
    )

    # Optional: Position Ledger
    position_ledger_db_path: Path = Field(
        default=Path("./positions.db"),
        alias="POSITION_LEDGER_DB_PATH",
        description="Path to SQLite position ledger database",
    )

    # Optional: Dead Letter Queue
    dead_letter_path: Path = Field(
        default=Path("./dead_letter_queue.jsonl"),
        alias="DEAD_LETTER_PATH",
        description="Path to dead letter queue for malformed events",
    )

    # Optional: Reconciliation Configuration
    reconciliation_interval_seconds: int = Field(
        default=15,
        alias="RECONCILIATION_INTERVAL_SECONDS",
        ge=1,
        description="Interval between reconciliation checks (seconds)",
    )

    drift_tolerance_qty: float = Field(
        default=0.1,
        alias="DRIFT_TOLERANCE_QTY",
        gt=0,
        description="Position quantity drift tolerance threshold",
    )

    drift_tolerance_price: float = Field(
        default=0.01,
        alias="DRIFT_TOLERANCE_PRICE",
        gt=0,
        description="Price drift tolerance threshold",
    )

    # Optional: Flask Configuration
    flask_env: str = Field(
        default="production",
        alias="FLASK_ENV",
        description="Flask environment (development/production)",
    )

    flask_debug: bool = Field(
        default=False,
        alias="FLASK_DEBUG",
        description="Enable Flask debug mode",
    )

    def validate_paths(self) -> None:
        """
        Ensure all required directories exist.

        Creates parent directories for all configured paths if they don't exist.
        """
        paths_to_create = [
            self.queue_path.parent,
            self.offset_path.parent,
            self.idempotency_db_path.parent,
            self.event_log_path.parent,
            self.position_ledger_db_path.parent,
            self.dead_letter_path.parent,
        ]

        for path in paths_to_create:
            path.mkdir(parents=True, exist_ok=True)

        logger.info("Validated all configuration paths")

    def log_config(self) -> None:
        """
        Log configuration (excluding secrets).

        Logs all non-sensitive configuration values for debugging.
        Never logs WEBHOOK_SECRET or TELEGRAM_TOKEN.
        """
        logger.info("Configuration loaded:")
        logger.info(f"  QUEUE_PATH: {self.queue_path}")
        logger.info(f"  OFFSET_PATH: {self.offset_path}")
        logger.info(f"  IDEMPOTENCY_DB_PATH: {self.idempotency_db_path}")
        logger.info(f"  EVENT_LOG_PATH: {self.event_log_path}")
        logger.info(f"  POSITION_LEDGER_DB_PATH: {self.position_ledger_db_path}")
        logger.info(f"  DEAD_LETTER_PATH: {self.dead_letter_path}")
        logger.info(
            f"  RECONCILIATION_INTERVAL_SECONDS: {self.reconciliation_interval_seconds}"
        )
        logger.info(f"  DRIFT_TOLERANCE_QTY: {self.drift_tolerance_qty}")
        logger.info(f"  DRIFT_TOLERANCE_PRICE: {self.drift_tolerance_price}")
        logger.info(f"  FLASK_ENV: {self.flask_env}")
        logger.info(f"  FLASK_DEBUG: {self.flask_debug}")
        logger.info("  WEBHOOK_SECRET: ***REDACTED***")
        logger.info("  TELEGRAM_TOKEN: ***REDACTED***")
        logger.info(f"  TELEGRAM_CHAT_ID: {self.telegram_chat_id}")


# Global settings instance (lazy loaded)
_settings: Optional[Settings] = None


def get_settings() -> Settings:
    """
    Get or create the global settings instance.

    Returns:
        Settings object loaded from environment variables

    Raises:
        ValidationError: If required environment variables are missing

    Example:
        >>> settings = get_settings()
        >>> print(settings.queue_path)
    """
    global _settings

    if _settings is None:
        _settings = Settings()
        _settings.validate_paths()
        _settings.log_config()

    return _settings


def reset_settings() -> None:
    """
    Reset global settings instance (for testing).

    Example:
        >>> reset_settings()  # Force reload from environment
        >>> settings = get_settings()
    """
    global _settings
    _settings = None
