#!/usr/bin/env python3
"""Generate per-symbol optimized Pine Script files from tournament results."""
import csv, os, re

STRAT_DIR = "/home/ubuntu/tradingview_webhook_bot/strategies"
CSV_PATH  = "/home/ubuntu/tradingview_webhook_bot/storage/reports/tournament_winners_4h.csv"

# Template → (filename, length_param, mult_param)
TEMPLATES = {
    "ichimoku trend pro":  ("ichimoku_trend_pro_4h_webhook.pine",  "tenkan_len", "kijun_mult"),
    "aggressive entry":    ("aggressive_entry_4h_webhook.pine",     "rsi_len",    "atr_mult"),
    "macd breakout":       ("macd_breakout_4h_webhook.pine",        "macd_len",   "atr_mult"),
    "keltner breakout":    ("keltner_breakout_4h_webhook.pine",     "kc_len",     "kc_mult"),
    "ichimoku macd pro":   ("ichimoku_macd_pro_4h_webhook.pine",    "tenkan_len", "kijun_mult"),
}

def find_template(strategy_name):
    s = strategy_name.lower()
    for key, val in TEMPLATES.items():
        if key in s:
            return val
    return None

def make_pine(symbol, strategy, roi, mult, length, template_file, len_param, mult_param):
    tpl_path = os.path.join(STRAT_DIR, template_file)
    if not os.path.exists(tpl_path):
        return None
    with open(tpl_path) as f:
        code = f.read()

    safe_s  = strategy.replace(' ','_').replace('/','_')[:20]
    title   = symbol + " | " + strategy + " [4H Optimized]"
    short   = symbol[:4] + "-" + safe_s[:8]

    # Replace strategy title and shorttitle
    code = re.sub(r'strategy\(".*?"', 'strategy("' + title + '"', code, count=1)
    code = re.sub(r'shorttitle=".*?"', 'shorttitle="' + short + '"', code, count=1)

    # Replace default length
    code = re.sub(
        r'(' + re.escape(len_param) + r'\s*=\s*input\.int\()(\d+)',
        lambda m: m.group(1) + str(int(float(length))),
        code, count=1
    )
    # Replace default mult
    code = re.sub(
        r'(' + re.escape(mult_param) + r'\s*=\s*input\.float\()([0-9.]+)',
        lambda m: m.group(1) + str(float(mult)),
        code, count=1
    )

    # Build header
    header_lines = [
        "//@version=5",
        "// Symbol-Optimized Script — Auto-Generated",
        "// Symbol   : " + symbol,
        "// Strategy : " + strategy,
        "// Daily ROI: " + str(roi) + "%  |  Tier: ALPHA++",
        "// Params   : " + len_param + "=" + str(length) + "  " + mult_param + "=" + str(mult),
        "// Webhook  : https://tradingbot.operatorbrief.xyz/webhook",
        "// Generated by tournament optimizer",
        "",
    ]
    header = "\n".join(header_lines) + "\n"
    # Remove existing @version=5 line and prepend header
    code = re.sub(r'^//@version=5\s*\n', '', code)
    code = header + code
    return code

# Read and sort
rows = []
with open(CSV_PATH) as f:
    for r in csv.DictReader(f):
        rows.append(r)
rows.sort(key=lambda x: float(x.get("Daily_ROI_%", 0)), reverse=True)

seen = set()
generated = []
skipped   = []

for r in rows:
    sym    = r["Symbol"]
    strat  = r["Strategy"]
    roi    = r["Daily_ROI_%"]
    mult   = r["Optimal_Mult"]
    length = r["Optimal_Len"]
    tier   = r["Tier"]

    if tier != "ALPHA++":
        continue
    key = sym + "|" + strat
    if key in seen:
        continue
    seen.add(key)

    tpl = find_template(strat)
    if not tpl:
        skipped.append(sym + " | " + strat + " (no template)")
        continue

    template_file, len_param, mult_param = tpl
    code = make_pine(sym, strat, roi, mult, length, template_file, len_param, mult_param)
    if not code:
        skipped.append(sym + " | " + strat + " (template file missing)")
        continue

    safe_strat = re.sub(r"[^a-z0-9]+", "_", strat.lower()).strip("_")[:25]
    fname = sym + "_" + safe_strat + "_4h.pine"
    fpath = os.path.join(STRAT_DIR, fname)
    with open(fpath, "w") as f:
        f.write(code)
    generated.append(fname)
    print("CREATED: " + fname + "  ROI=" + roi + "%")

print("\n=== DONE: " + str(len(generated)) + " scripts generated ===")
if skipped:
    print("Skipped (" + str(len(skipped)) + "):")
    for s in skipped:
        print("  " + s)
