# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Abstract base class for exchange adapters.

This module defines the interface that all exchange adapters must implement,
including the MockExchange adapter for testing.
"""

from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Optional

from trading_bot.schemas import ClientOrder, Fill, OrderSide, Venue


class ExchangeAdapter(ABC):
    """
    Abstract base class for exchange adapters.

    All exchange implementations (Binance, Hyperliquid, Mock) must implement
    this interface to ensure consistent behavior across different venues.
    """

    @property
    @abstractmethod
    def venue(self) -> Venue:
        """
        Get the venue name for this adapter.

        Returns:
            Venue enum value
        """
        pass

    @abstractmethod
    def place_order(
        self,
        client_order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: Decimal,
        order_type: str = "MARKET",
    ) -> ClientOrder:
        """
        Place an order on the exchange.

        Args:
            client_order_id: Deterministic order ID
            symbol: Trading pair (e.g., "BTCUSDT")
            side: Order side (BUY/SELL)
            quantity: Order quantity
            order_type: Order type (default: "MARKET")

        Returns:
            ClientOrder with exchange_order_id populated

        Raises:
            Exception: If order placement fails

        Example:
            >>> adapter = MockExchange()
            >>> order = adapter.place_order(
            ...     client_order_id="TV-20260116-test-a1b2:MOCK:ENTRY:1",
            ...     symbol="BTCUSDT",
            ...     side=OrderSide.BUY,
            ...     quantity=Decimal("0.001")
            ... )
            >>> print(order.exchange_order_id)
        """
        pass

    @abstractmethod
    def get_fills(self, exchange_order_id: str) -> list[Fill]:
        """
        Get fills for an order.

        Args:
            exchange_order_id: Order ID from exchange

        Returns:
            List of Fill objects (may be empty if order not filled)

        Raises:
            Exception: If query fails

        Example:
            >>> adapter = MockExchange()
            >>> fills = adapter.get_fills("MOCK-ORDER-12345")
            >>> for fill in fills:
            ...     print(f"Filled {fill.filled_qty} at {fill.fill_price}")
        """
        pass

    @abstractmethod
    def get_position(self, symbol: str) -> Decimal:
        """
        Get current position quantity for a symbol.

        Args:
            symbol: Trading pair (e.g., "BTCUSDT")

        Returns:
            Net position quantity (positive=LONG, negative=SHORT, zero=FLAT)

        Raises:
            Exception: If query fails

        Example:
            >>> adapter = MockExchange()
            >>> position_qty = adapter.get_position("BTCUSDT")
            >>> print(f"Position: {position_qty}")
        """
        pass

    @abstractmethod
    def close(self) -> None:
        """
        Close any open connections or resources.

        Example:
            >>> adapter = MockExchange()
            >>> # ... use adapter ...
            >>> adapter.close()
        """
        pass
