# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Mock exchange adapter for testing without real API calls.

This adapter simulates immediate order fills with deterministic IDs.
Used in all tests and MVP implementation before connecting real exchanges.
"""

import logging
from datetime import datetime
from decimal import Decimal
from typing import Optional
from uuid import uuid4

from trading_bot.data_sources.exchange_base import ExchangeAdapter
from trading_bot.schemas import (
    ClientOrder,
    Fill,
    Leg,
    OrderSide,
    OrderStatus,
    OrderType,
    Venue,
)

logger = logging.getLogger(__name__)


class MockExchange(ExchangeAdapter):
    """
    Mock exchange adapter for testing.

    Simulates immediate fills with deterministic exchange_order_id and fill_id.
    Maintains internal position state for reconciliation testing.

    TODO: Replace with real exchange adapters before production deployment.
    """

    def __init__(self):
        """Initialize the mock exchange with empty position tracking."""
        self._positions: dict[str, Decimal] = {}  # symbol -> net_quantity
        logger.info("Initialized MockExchange adapter")

    @property
    def venue(self) -> Venue:
        """Get venue name."""
        return Venue.MOCK

    def place_order(
        self,
        client_order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: Decimal,
        order_type: str = "MARKET",
    ) -> ClientOrder:
        """
        Place a mock order (simulates immediate fill).

        Args:
            client_order_id: Deterministic order ID
            symbol: Trading pair
            side: Order side (BUY/SELL)
            quantity: Order quantity
            order_type: Order type (default: "MARKET")

        Returns:
            ClientOrder with FILLED status and mock exchange_order_id

        Example:
            >>> mock = MockExchange()
            >>> order = mock.place_order(
            ...     client_order_id="TV-20260116-test-a1b2:MOCK:ENTRY:1",
            ...     symbol="BTCUSDT",
            ...     side=OrderSide.BUY,
            ...     quantity=Decimal("0.001")
            ... )
            >>> assert order.status == OrderStatus.FILLED
        """
        # Extract signal_id from client_order_id
        signal_id = client_order_id.split(":")[0]

        # Generate deterministic exchange_order_id
        exchange_order_id = f"MOCK-{signal_id}-{uuid4().hex[:8].upper()}"

        # Parse leg and attempt from client_order_id
        parts = client_order_id.split(":")
        leg = Leg(parts[2])
        attempt = int(parts[3])

        # Create order with FILLED status (immediate fill)
        order = ClientOrder(
            client_order_id=client_order_id,
            signal_id=signal_id,
            venue=Venue.MOCK,
            leg=leg,
            attempt=attempt,
            side=side,
            symbol=symbol,
            quantity=quantity,
            order_type=OrderType(order_type),
            status=OrderStatus.FILLED,
            exchange_order_id=exchange_order_id,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        )

        # Update internal position tracking
        signed_qty = quantity if side == OrderSide.BUY else -quantity
        current_position = self._positions.get(symbol, Decimal("0"))
        self._positions[symbol] = current_position + signed_qty

        logger.info(
            f"MockExchange placed order: {client_order_id} -> {exchange_order_id} "
            f"({side} {quantity} {symbol}). New position: {self._positions[symbol]}"
        )

        return order

    def get_fills(self, exchange_order_id: str) -> list[Fill]:
        """
        Get fills for a mock order (returns single immediate fill).

        Args:
            exchange_order_id: Order ID from place_order

        Returns:
            List with single Fill object (full quantity filled immediately)

        Example:
            >>> mock = MockExchange()
            >>> order = mock.place_order("TV-test:MOCK:ENTRY:1", "BTCUSDT", OrderSide.BUY, Decimal("0.001"))
            >>> fills = mock.get_fills(order.exchange_order_id)
            >>> assert len(fills) == 1
        """
        # Extract client_order_id from exchange_order_id
        # Format: MOCK-{signal_id}-{random8}
        parts = exchange_order_id.split("-")
        if len(parts) < 3 or parts[0] != "MOCK":
            raise ValueError(f"Invalid mock exchange_order_id: {exchange_order_id}")

        # Simulate immediate fill at mock price (90000 for all symbols in MVP)
        mock_price = Decimal("90000.00")
        mock_quantity = Decimal("0.001")  # Default quantity for MVP

        fill = Fill(
            fill_id=f"FILL-{exchange_order_id}",
            client_order_id=f"TV-{parts[1]}-{parts[2]}:MOCK:ENTRY:1",  # Reconstruct client_order_id
            exchange_order_id=exchange_order_id,
            filled_qty=mock_quantity,
            fill_price=mock_price,
            fee=Decimal("0.0"),  # No fees in mock
            fee_asset=None,
            timestamp=datetime.utcnow(),
            venue=Venue.MOCK,
        )

        logger.debug(f"MockExchange returning fill for {exchange_order_id}: {fill.fill_id}")

        return [fill]

    def get_position(self, symbol: str) -> Decimal:
        """
        Get current mock position quantity.

        Args:
            symbol: Trading pair

        Returns:
            Net position quantity from internal tracking

        Example:
            >>> mock = MockExchange()
            >>> mock.place_order("TV-test:MOCK:ENTRY:1", "BTCUSDT", OrderSide.BUY, Decimal("0.5"))
            >>> position = mock.get_position("BTCUSDT")
            >>> assert position == Decimal("0.5")
        """
        position = self._positions.get(symbol, Decimal("0"))
        logger.debug(f"MockExchange position for {symbol}: {position}")
        return position

    def close(self) -> None:
        """Close mock exchange (no-op)."""
        logger.info("Closed MockExchange adapter")
        pass
