# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
TradingView queue consumer with idempotency and execution.

This module wires together the JsonlOffsetConsumer, IdempotencyStore,
and Executor to process signals from the queue.
"""

import logging
from datetime import datetime
from typing import Any

from trading_bot.config_manager.settings import get_settings
from trading_bot.data_sources.exchange_base import ExchangeAdapter
from trading_bot.data_sources.mock_exchange import MockExchange
from trading_bot.execution.executor import execute_signal
from trading_bot.schemas import TradingSignal
from trading_bot.storage.idempotency_store import IdempotencyStore
from trading_bot.storage.jsonl_consumer import JsonlOffsetConsumer
from trading_bot.storage.jsonl_queue import append_jsonl

logger = logging.getLogger(__name__)


def consume_signals(
    adapter: ExchangeAdapter | None = None,
    max_events: int = 1,
) -> int:
    """
    Consume signals from queue with idempotency checking and execution.

    This is the main consumer function that:
    1. Polls the JSONL queue for new signals
    2. Checks idempotency store to prevent duplicates
    3. Executes signal via adapter (or MockExchange if not provided)
    4. Updates idempotency store status
    5. Advances offset checkpoint

    Args:
        adapter: Exchange adapter to use (defaults to MockExchange)
        max_events: Maximum number of signals to process (default: 1)

    Returns:
        Number of signals successfully processed

    Example:
        >>> from trading_bot.data_sources.mock_exchange import MockExchange
        >>> processed = consume_signals(adapter=MockExchange(), max_events=5)
        >>> print(f"Processed {processed} signals")
    """
    settings = get_settings()

    # Use MockExchange if no adapter provided (MVP default)
    if adapter is None:
        adapter = MockExchange()
        logger.info("Using MockExchange adapter (MVP mode)")

    # Initialize consumer and idempotency store
    consumer = JsonlOffsetConsumer(
        queue_path=settings.queue_path,
        offset_path=settings.offset_path,
        dead_letter_path=settings.dead_letter_path,
    )

    idempotency_store = IdempotencyStore(settings.idempotency_db_path)

    # Create handler function with closure over dependencies
    def signal_handler(event: dict[str, Any]) -> None:
        """
        Handle a single signal from the queue.

        Args:
            event: Signal dictionary from JSONL queue

        Raises:
            Exception: If processing fails (offset not advanced)
        """
        # Parse signal
        signal = TradingSignal(**event)

        logger.info(f"Processing signal: {signal.signal_id}")

        # Log signal_processing_started
        log_signal_processing_started(signal, settings)

        # Check idempotency
        if idempotency_store.seen(signal.signal_id):
            logger.info(f"Signal {signal.signal_id} already processed (duplicate detected)")
            log_duplicate_detected(signal, settings)
            return  # Skip processing

        # Mark as PROCESSING
        if not idempotency_store.mark_processing(signal.signal_id):
            logger.warning(
                f"Failed to mark signal {signal.signal_id} as PROCESSING "
                "(already exists - race condition or duplicate)"
            )
            return  # Skip processing

        try:
            # Execute signal
            result = execute_signal(signal, adapter)

            if result.success:
                # Mark as DONE
                idempotency_store.mark_done(signal.signal_id)
                logger.info(f"Signal {signal.signal_id} processed successfully")
                log_signal_processing_completed(signal, settings)
            else:
                # Mark as FAILED
                idempotency_store.mark_failed(signal.signal_id, result.error_message)
                logger.error(f"Signal {signal.signal_id} execution failed")
                log_signal_processing_failed(signal, result.error_message or "Unknown error", settings)

        except Exception as e:
            # Mark as FAILED and re-raise
            error_msg = str(e)
            idempotency_store.mark_failed(signal.signal_id, error_msg)
            logger.error(f"Signal {signal.signal_id} processing failed: {e}", exc_info=True)
            log_signal_processing_failed(signal, error_msg, settings)
            raise  # Re-raise to prevent offset advance

    # Poll consumer
    processed_count = consumer.poll(handler=signal_handler, max_events=max_events)

    logger.info(f"Consumer poll completed: {processed_count} signals processed")

    return processed_count


def log_signal_processing_started(signal: TradingSignal, settings) -> None:
    """Log signal_processing_started event."""
    event = {
        "event_type": "signal_processing_started",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "strategy": signal.strategy,
        "side": signal.side.value,
        "symbol": signal.symbol,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log signal_processing_started: {e}")


def log_duplicate_detected(signal: TradingSignal, settings) -> None:
    """Log duplicate_detected event."""
    event = {
        "event_type": "duplicate_detected",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "strategy": signal.strategy,
        "side": signal.side.value,
        "symbol": signal.symbol,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log duplicate_detected: {e}")


def log_signal_processing_completed(signal: TradingSignal, settings) -> None:
    """Log signal_processing_completed event."""
    event = {
        "event_type": "signal_processing_completed",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log signal_processing_completed: {e}")


def log_signal_processing_failed(signal: TradingSignal, error_message: str, settings) -> None:
    """Log signal_processing_failed event."""
    event = {
        "event_type": "signal_processing_failed",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "error_message": error_message,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log signal_processing_failed: {e}")
