# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Position ledger for tracking derived positions from fills.

This module maintains position state by applying fills and provides
position queries for reconciliation.
"""

import logging
import sqlite3
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Optional

from trading_bot.schemas import OrderSide, Position, Venue

logger = logging.getLogger(__name__)


class PositionLedger:
    """
    SQLite-based position ledger.

    Tracks derived positions by applying fills. Positions are keyed by
    (strategy_id, symbol, venue) and updated atomically using transactions.
    """

    def __init__(self, sqlite_path: str | Path):
        """
        Initialize the position ledger.

        Args:
            sqlite_path: Path to SQLite database file

        Example:
            >>> ledger = PositionLedger("positions.db")
        """
        self.sqlite_path = Path(sqlite_path)
        self.sqlite_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _init_db(self) -> None:
        """Create positions table if it doesn't exist."""
        with sqlite3.connect(self.sqlite_path) as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS positions (
                    strategy_id TEXT NOT NULL,
                    symbol TEXT NOT NULL,
                    venue TEXT NOT NULL CHECK(venue IN ('BINANCE', 'HYPERLIQUID', 'MOCK')),
                    quantity TEXT NOT NULL,
                    avg_entry_price TEXT,
                    total_fees TEXT NOT NULL DEFAULT '0.0',
                    realized_pnl TEXT NOT NULL DEFAULT '0.0',
                    last_updated TEXT NOT NULL,
                    PRIMARY KEY (strategy_id, symbol, venue)
                )
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_venue ON positions(venue)")
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_last_updated ON positions(last_updated)"
            )
            conn.commit()

        logger.info(f"Initialized position ledger at {self.sqlite_path}")

    def apply_fill(
        self,
        strategy_id: str,
        symbol: str,
        venue: Venue,
        side: OrderSide,
        qty: Decimal,
        price: Decimal,
        fee: Decimal = Decimal("0.0"),
    ) -> None:
        """
        Apply a fill to update position.

        Args:
            strategy_id: Strategy name
            symbol: Trading pair
            venue: Exchange venue
            side: Order side (BUY/SELL)
            qty: Filled quantity (positive)
            price: Fill price
            fee: Fee charged (default: 0.0)

        Example:
            >>> ledger = PositionLedger("positions.db")
            >>> ledger.apply_fill("smc_luxalgo", "BTCUSDT", Venue.MOCK, OrderSide.BUY, Decimal("0.5"), Decimal("90000"))
        """
        if qty <= 0:
            raise ValueError(f"Quantity must be positive, got {qty}")
        if price <= 0:
            raise ValueError(f"Price must be positive, got {price}")
        if fee < 0:
            raise ValueError(f"Fee must be non-negative, got {fee}")

        # Convert side to signed quantity (BUY=+, SELL=-)
        signed_qty = qty if side == OrderSide.BUY else -qty

        with sqlite3.connect(self.sqlite_path) as conn:
            # Get current position
            cursor = conn.execute(
                """
                SELECT quantity, avg_entry_price, total_fees, realized_pnl
                FROM positions
                WHERE strategy_id = ? AND symbol = ? AND venue = ?
                """,
                (strategy_id, symbol, venue.value),
            )
            result = cursor.fetchone()

            if result is None:
                # New position
                new_qty = signed_qty
                new_avg_price = price if new_qty != 0 else None
                new_total_fees = fee
                new_realized_pnl = Decimal("0.0")
            else:
                # Update existing position
                current_qty = Decimal(result[0])
                current_avg_price = Decimal(result[1]) if result[1] else None
                current_fees = Decimal(result[2])
                current_pnl = Decimal(result[3])

                new_qty = current_qty + signed_qty
                new_total_fees = current_fees + fee

                # Update avg_entry_price (simple weighted average for increasing position)
                if current_qty == 0:
                    # Opening new position
                    new_avg_price = price if new_qty != 0 else None
                    new_realized_pnl = current_pnl
                elif (current_qty > 0 and signed_qty > 0) or (current_qty < 0 and signed_qty < 0):
                    # Adding to position - weighted average
                    total_cost = (abs(current_qty) * current_avg_price) + (abs(signed_qty) * price)
                    new_avg_price = total_cost / abs(new_qty) if new_qty != 0 else None
                    new_realized_pnl = current_pnl
                else:
                    # Reducing or closing position - realize PnL
                    if current_avg_price:
                        pnl_per_unit = (price - current_avg_price) if current_qty > 0 else (current_avg_price - price)
                        realized_qty = min(abs(current_qty), abs(signed_qty))
                        realized_pnl_delta = pnl_per_unit * realized_qty
                        new_realized_pnl = current_pnl + realized_pnl_delta
                    else:
                        new_realized_pnl = current_pnl

                    # Keep old avg price if position not fully closed
                    new_avg_price = current_avg_price if new_qty != 0 else None

            # Upsert position
            conn.execute(
                """
                INSERT OR REPLACE INTO positions
                (strategy_id, symbol, venue, quantity, avg_entry_price, total_fees, realized_pnl, last_updated)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    strategy_id,
                    symbol,
                    venue.value,
                    str(new_qty),
                    str(new_avg_price) if new_avg_price else None,
                    str(new_total_fees),
                    str(new_realized_pnl),
                    datetime.utcnow().isoformat(),
                ),
            )
            conn.commit()

        logger.info(
            f"Applied fill: {strategy_id} {symbol} {venue.value} {side.value} {qty} @ {price}. "
            f"New position: {new_qty}"
        )

    def get_position(
        self, strategy_id: str, symbol: str, venue: Venue
    ) -> Optional[Position]:
        """
        Get current position.

        Args:
            strategy_id: Strategy name
            symbol: Trading pair
            venue: Exchange venue

        Returns:
            Position object or None if no position exists

        Example:
            >>> ledger = PositionLedger("positions.db")
            >>> position = ledger.get_position("smc_luxalgo", "BTCUSDT", Venue.MOCK)
            >>> if position:
            ...     print(f"Position: {position.quantity}")
        """
        with sqlite3.connect(self.sqlite_path) as conn:
            cursor = conn.execute(
                """
                SELECT quantity, avg_entry_price, total_fees, realized_pnl, last_updated
                FROM positions
                WHERE strategy_id = ? AND symbol = ? AND venue = ?
                """,
                (strategy_id, symbol, venue.value),
            )
            result = cursor.fetchone()

        if result is None:
            return None

        return Position(
            strategy_id=strategy_id,
            symbol=symbol,
            venue=venue,
            quantity=Decimal(result[0]),
            avg_entry_price=Decimal(result[1]) if result[1] else None,
            total_fees=Decimal(result[2]),
            realized_pnl=Decimal(result[3]),
            last_updated=datetime.fromisoformat(result[4]),
        )
