# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Order execution engine.

This module handles signal execution: generating orders, submitting to exchange,
processing fills, and logging execution events.
"""

import logging
from datetime import datetime
from decimal import Decimal
from typing import Optional

from trading_bot.config_manager.settings import get_settings
from trading_bot.data_sources.exchange_base import ExchangeAdapter
from trading_bot.execution.policies import calculate_quantity
from trading_bot.execution.router import select_venue
from trading_bot.schemas import (
    ClientOrder,
    Fill,
    Leg,
    OrderSide,
    OrderStatus,
    TradingSignal,
    Venue,
    derive_order_side,
    generate_client_order_id,
)
from trading_bot.storage.jsonl_queue import append_jsonl

logger = logging.getLogger(__name__)


class ExecutionResult:
    """Result of signal execution."""

    def __init__(
        self,
        signal_id: str,
        success: bool,
        order: Optional[ClientOrder] = None,
        fills: Optional[list[Fill]] = None,
        error_message: Optional[str] = None,
    ):
        """
        Initialize execution result.

        Args:
            signal_id: Signal ID that was executed
            success: Whether execution succeeded
            order: ClientOrder if order was placed
            fills: List of fills if order was filled
            error_message: Error message if execution failed
        """
        self.signal_id = signal_id
        self.success = success
        self.order = order
        self.fills = fills or []
        self.error_message = error_message


def execute_signal(signal: TradingSignal, adapter: ExchangeAdapter) -> ExecutionResult:
    """
    Execute a trading signal.

    Args:
        signal: Trading signal to execute
        adapter: Exchange adapter to use

    Returns:
        ExecutionResult with order and fills

    Raises:
        Exception: If execution fails critically

    Example:
        >>> from trading_bot.data_sources.mock_exchange import MockExchange
        >>> signal = TradingSignal(...)
        >>> adapter = MockExchange()
        >>> result = execute_signal(signal, adapter)
        >>> assert result.success
        >>> assert len(result.fills) > 0
    """
    settings = get_settings()

    try:
        # Log execution started
        log_execution_started(signal, settings)

        # Select venue (MVP always returns MOCK)
        venue = select_venue(signal)

        # Calculate quantity
        quantity = calculate_quantity(signal, venue)

        # Determine order side (BUY/SELL) from signal side (LONG/SHORT) and leg (ENTRY)
        # MVP only implements ENTRY orders
        leg = Leg.ENTRY
        order_side = derive_order_side(signal.side, leg)

        # Generate deterministic client_order_id
        client_order_id = generate_client_order_id(
            signal_id=signal.signal_id,
            venue=venue,
            leg=leg,
            attempt=1,
        )

        # Place order via adapter
        order = adapter.place_order(
            client_order_id=client_order_id,
            symbol=signal.symbol,
            side=order_side,
            quantity=quantity,
            order_type="MARKET",
        )

        # Log order placed
        log_order_placed(order, signal, settings)

        # Get fills
        fills = adapter.get_fills(order.exchange_order_id)

        # Log each fill
        for fill in fills:
            log_fill_received(fill, signal, settings)

        # Apply fills to position ledger (if ledger is available)
        # TODO: Initialize PositionLedger in bot_main.py and pass to executor
        # from trading_bot.ledger.positions import PositionLedger
        # for fill in fills:
        #     ledger.apply_fill(fill, signal.strategy)

        # Log execution completed
        log_execution_completed(signal, order, fills, settings)

        logger.info(
            f"Executed signal {signal.signal_id}: {order.status.value} "
            f"with {len(fills)} fills"
        )

        return ExecutionResult(
            signal_id=signal.signal_id,
            success=True,
            order=order,
            fills=fills,
        )

    except Exception as e:
        error_msg = f"Execution failed for signal {signal.signal_id}: {e}"
        logger.error(error_msg, exc_info=True)

        # Log execution failed
        log_execution_failed(signal, str(e), settings)

        return ExecutionResult(
            signal_id=signal.signal_id,
            success=False,
            error_message=error_msg,
        )


def log_execution_started(signal: TradingSignal, settings) -> None:
    """Log execution_started event."""
    event = {
        "event_type": "execution_started",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "strategy": signal.strategy,
        "side": signal.side.value,
        "symbol": signal.symbol,
        "price": str(signal.price),
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log execution_started: {e}")


def log_order_placed(order: ClientOrder, signal: TradingSignal, settings) -> None:
    """Log order_placed event."""
    event = {
        "event_type": "order_placed",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "client_order_id": order.client_order_id,
        "exchange_order_id": order.exchange_order_id,
        "venue": order.venue.value,
        "side": order.side.value,
        "symbol": order.symbol,
        "quantity": str(order.quantity),
        "order_type": order.order_type.value,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log order_placed: {e}")


def log_fill_received(fill: Fill, signal: TradingSignal, settings) -> None:
    """Log fill_received event."""
    event = {
        "event_type": "fill_received",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "client_order_id": fill.client_order_id,
        "exchange_order_id": fill.exchange_order_id,
        "fill_id": fill.fill_id,
        "filled_qty": str(fill.filled_qty),
        "fill_price": str(fill.fill_price),
        "fee": str(fill.fee),
        "venue": fill.venue.value,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log fill_received: {e}")


def log_execution_completed(
    signal: TradingSignal, order: ClientOrder, fills: list[Fill], settings
) -> None:
    """Log execution_completed event."""
    total_filled = sum(fill.filled_qty for fill in fills)
    event = {
        "event_type": "execution_completed",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "client_order_id": order.client_order_id,
        "exchange_order_id": order.exchange_order_id,
        "status": order.status.value,
        "total_filled_qty": str(total_filled),
        "fill_count": len(fills),
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log execution_completed: {e}")


def log_execution_failed(signal: TradingSignal, error_message: str, settings) -> None:
    """Log execution_failed event."""
    event = {
        "event_type": "execution_failed",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "error_message": error_message,
    }
    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log execution_failed: {e}")
