# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Execution router for venue selection.

This module determines which exchange to route orders to based on signal properties.
MVP implementation always routes to MockExchange.
"""

import logging

from trading_bot.schemas import Side, TradingSignal, Venue

logger = logging.getLogger(__name__)


def select_venue(signal: TradingSignal) -> Venue:
    """
    Select exchange venue for order execution.

    Args:
        signal: Trading signal to execute

    Returns:
        Venue enum value

    Example:
        >>> signal = TradingSignal(...)
        >>> venue = select_venue(signal)
        >>> assert venue == Venue.MOCK  # MVP always returns MOCK
    """
    # TODO: Implement multi-venue routing logic for production
    # For now, always route to MockExchange (MVP requirement)
    venue = Venue.MOCK

    logger.debug(f"Selected venue {venue.value} for signal {signal.signal_id}")

    return venue
