# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
TradingView Webhook Production System

A production-grade trading bot that receives TradingView alerts via webhook,
processes them idempotently, and executes orders with full traceability.
"""

__version__ = "1.0.0"
