# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Main bot consumer entrypoint.

This module runs the signal consumer in a loop, processing signals
from the TradingView webhook queue.
"""

import logging
import time
from signal import SIGINT, SIGTERM, signal

from trading_bot.data_sources.mock_exchange import MockExchange
from trading_bot.data_sources.tradingview_queue import consume_signals

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Global flag for graceful shutdown
_shutdown_requested = False


def signal_handler(signum, frame):
    """Handle shutdown signals gracefully."""
    global _shutdown_requested
    logger.info(f"Received signal {signum}, initiating graceful shutdown...")
    _shutdown_requested = True


def main():
    """
    Main consumer loop.

    Continuously polls the queue for new signals and processes them.
    Handles graceful shutdown on SIGINT/SIGTERM.
    """
    # Register signal handlers
    signal(SIGINT, signal_handler)
    signal(SIGTERM, signal_handler)

    logger.info("Starting TradingView signal consumer...")

    # TODO: Replace MockExchange with real exchange adapters before production
    adapter = MockExchange()

    try:
        while not _shutdown_requested:
            try:
                # Process up to 5 signals per poll
                processed = consume_signals(adapter=adapter, max_events=5)

                if processed == 0:
                    # No signals to process, sleep briefly
                    time.sleep(1)
                else:
                    # Signals processed, poll immediately for more
                    logger.debug(f"Processed {processed} signals, polling again...")

            except KeyboardInterrupt:
                logger.info("KeyboardInterrupt received, shutting down...")
                break

            except Exception as e:
                logger.error(f"Consumer error: {e}", exc_info=True)
                # Sleep before retry on error
                time.sleep(5)

    finally:
        # Cleanup
        adapter.close()
        logger.info("Consumer shut down gracefully")


if __name__ == "__main__":
    main()
