# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Pydantic schemas for TradingView Webhook Production System.

This module defines all data models and validation rules for the trading bot.
All models use Pydantic v2 for runtime validation and type safety.
"""

import os
import random
import string
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator, model_validator


# ============================================================================
# Enums
# ============================================================================


class Side(str, Enum):
    """Trade direction from TradingView signal."""

    LONG = "LONG"
    SHORT = "SHORT"


class OrderSide(str, Enum):
    """Order side for exchange submission."""

    BUY = "BUY"
    SELL = "SELL"


class Venue(str, Enum):
    """Exchange venue for order execution."""

    BINANCE = "BINANCE"
    HYPERLIQUID = "HYPERLIQUID"
    MOCK = "MOCK"


class Leg(str, Enum):
    """Order purpose in strategy lifecycle."""

    ENTRY = "ENTRY"
    EXIT = "EXIT"


class OrderType(str, Enum):
    """Order type for exchange submission."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(str, Enum):
    """Order execution status."""

    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FAILED = "FAILED"


class IdempotencyStatus(str, Enum):
    """Idempotency key processing status."""

    PROCESSING = "PROCESSING"
    DONE = "DONE"
    FAILED = "FAILED"


class ReconciliationStatus(str, Enum):
    """Reconciliation check result."""

    MATCH = "MATCH"
    DRIFT = "DRIFT"
    ERROR = "ERROR"


class AlertSeverity(str, Enum):
    """Alert priority level."""

    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertChannel(str, Enum):
    """Notification channel."""

    TELEGRAM = "TELEGRAM"
    SLACK = "SLACK"


# ============================================================================
# Core Models
# ============================================================================


class TradingSignalRequest(BaseModel):
    """
    Webhook request payload from TradingView.

    This model validates incoming webhook requests before processing.
    The secret field is validated but never persisted or logged.
    
    Accepts both 'side' and 'signal' fields for backward compatibility.
    """

    secret: str = Field(..., description="Webhook secret for authentication")
    strategy: str = Field(..., min_length=1, max_length=100, description="Strategy name")
    side: Optional[Side] = Field(None, description="Trade direction (LONG/SHORT) - use either 'side' or 'signal'")
    signal: Optional[Side] = Field(None, description="Trade direction (LONG/SHORT) - legacy field name")
    symbol: str = Field(..., pattern=r"^[A-Z]{2,10}USDT?$", description="Trading pair")
    price: Decimal = Field(..., gt=0, description="Signal price from TradingView")
    timeframe: str = Field(..., pattern=r"^\d+[mhd]$", description="Chart timeframe")
    
    @property
    def trade_side(self) -> Side:
        """Get trade direction from either 'side' or 'signal' field."""
        return self.side or self.signal
    
    def model_post_init(self, __context) -> None:
        """Validate that at least one of 'side' or 'signal' is provided."""
        if not self.side and not self.signal:
            raise ValueError("Either 'side' or 'signal' field must be provided")
        # Normalize: if signal is provided but not side, copy it to side
        if self.signal and not self.side:
            self.side = self.signal

    class Config:
        """Pydantic configuration."""

        json_schema_extra = {
            "example": {
                "secret": "hybrid_tradingview_cluster_2026_secure",
                "strategy": "Smart Money Concepts [LuxAlgo]",
                "side": "LONG",
                "symbol": "BTCUSDT",
                "price": "90750.00",
                "timeframe": "15m",
            }
        }


class TradingSignal(BaseModel):
    """
    Validated trading signal after webhook ingestion.

    This is the immutable signal stored in the JSONL queue.
    The secret field is NOT included (validation only, never persisted).
    """

    signal_id: str = Field(
        ..., pattern=r"^TV-\d{14}-\w+-\w{4}$", description="Unique signal identifier"
    )
    strategy: str = Field(..., min_length=1, max_length=100, description="Strategy name")
    side: Side = Field(..., description="Trade direction (LONG/SHORT)")
    symbol: str = Field(..., pattern=r"^[A-Z]{2,10}USDT?$", description="Trading pair")
    price: Decimal = Field(..., gt=0, description="Signal price")
    timeframe: str = Field(..., pattern=r"^\d+[mhd]$", description="Chart timeframe")
    timestamp: datetime = Field(..., description="When signal was received (ISO8601)")

    class Config:
        """Pydantic configuration."""

        frozen = True  # Immutable after creation
        json_encoders = {Decimal: str, datetime: lambda v: v.isoformat()}


class ClientOrder(BaseModel):
    """
    Order submitted to exchange (or MockExchange).

    The client_order_id is deterministic and enables idempotent order placement.
    """

    client_order_id: str = Field(
        ...,
        pattern=r"^TV-\d{14}-\w+-\w{4}:(BINANCE|HYPERLIQUID|MOCK):(ENTRY|EXIT):\d+$",
        description="Deterministic order ID",
    )
    signal_id: str = Field(..., description="Foreign key to TradingSignal")
    venue: Venue = Field(..., description="Exchange name")
    leg: Leg = Field(..., description="Order purpose (ENTRY/EXIT)")
    attempt: int = Field(..., ge=1, description="Retry attempt number (1-indexed)")
    side: OrderSide = Field(..., description="Order side (BUY/SELL)")
    symbol: str = Field(..., description="Trading pair")
    quantity: Decimal = Field(..., gt=0, description="Order quantity")
    order_type: OrderType = Field(..., description="Order type (MARKET/LIMIT)")
    status: OrderStatus = Field(..., description="Order execution status")
    exchange_order_id: Optional[str] = Field(
        None, description="Order ID from exchange (null until submitted)"
    )
    created_at: datetime = Field(..., description="When order was created")
    updated_at: datetime = Field(..., description="Last status update timestamp")

    class Config:
        """Pydantic configuration."""

        json_encoders = {Decimal: str, datetime: lambda v: v.isoformat()}


class Fill(BaseModel):
    """
    Partial or complete order fill from exchange.

    Fills are immutable and append-only.
    """

    fill_id: str = Field(..., description="Unique fill identifier")
    client_order_id: str = Field(..., description="Foreign key to ClientOrder")
    exchange_order_id: str = Field(..., description="Order ID from exchange")
    filled_qty: Decimal = Field(..., gt=0, description="Quantity filled in this event")
    fill_price: Decimal = Field(..., gt=0, description="Execution price for this fill")
    fee: Decimal = Field(default=Decimal("0.0"), ge=0, description="Fee charged by exchange")
    fee_asset: Optional[str] = Field(None, description="Asset used for fee (e.g., USDT, BNB)")
    timestamp: datetime = Field(..., description="When fill occurred (from exchange)")
    venue: Venue = Field(..., description="Exchange that executed fill")

    class Config:
        """Pydantic configuration."""

        frozen = True  # Immutable
        json_encoders = {Decimal: str, datetime: lambda v: v.isoformat()}


class Position(BaseModel):
    """
    Derived position state for (strategy, symbol, venue) tuple.

    Updated via PositionLedger.apply_fill() when fills arrive.
    """

    strategy_id: str = Field(..., description="Strategy name from signal")
    symbol: str = Field(..., description="Trading pair")
    venue: Venue = Field(..., description="Exchange")
    quantity: Decimal = Field(
        ..., description="Net position (positive=LONG, negative=SHORT, zero=FLAT)"
    )
    avg_entry_price: Optional[Decimal] = Field(
        None, gt=0, description="Average entry price (null when quantity=0)"
    )
    total_fees: Decimal = Field(
        default=Decimal("0.0"), ge=0, description="Cumulative fees paid"
    )
    realized_pnl: Decimal = Field(
        default=Decimal("0.0"), description="Realized profit/loss (basic calculation)"
    )
    last_updated: datetime = Field(..., description="When position was last modified")

    @model_validator(mode="after")
    def validate_avg_entry_price(self) -> "Position":
        """Validate avg_entry_price is null when quantity is zero."""
        if self.quantity == 0 and self.avg_entry_price is not None:
            raise ValueError("avg_entry_price must be null when quantity is zero")
        if self.quantity != 0 and self.avg_entry_price is None:
            raise ValueError("avg_entry_price must be set when quantity is non-zero")
        return self

    class Config:
        """Pydantic configuration."""

        json_encoders = {Decimal: str, datetime: lambda v: v.isoformat()}


class ReconciliationEvent(BaseModel):
    """
    Reconciliation check comparing derived vs exchange-reported position.

    Immutable event log for audit trail.
    """

    reconciliation_id: str = Field(default_factory=lambda: str(uuid4()), description="UUID v4")
    strategy_id: str = Field(..., description="Strategy being reconciled")
    symbol: str = Field(..., description="Trading pair being reconciled")
    venue: Venue = Field(..., description="Exchange being checked")
    derived_qty: Decimal = Field(..., description="Quantity from PositionLedger")
    exchange_qty: Decimal = Field(..., description="Quantity reported by exchange API")
    drift: Decimal = Field(..., ge=0, description="Absolute difference (abs(derived - exchange))")
    tolerance_qty: Decimal = Field(..., gt=0, description="Configured tolerance threshold")
    status: ReconciliationStatus = Field(..., description="Reconciliation result")
    timestamp: datetime = Field(..., description="When reconciliation was performed")
    error_message: Optional[str] = Field(None, description="Error details if status=ERROR")

    class Config:
        """Pydantic configuration."""

        frozen = True  # Immutable
        json_encoders = {Decimal: str, datetime: lambda v: v.isoformat()}


class Alert(BaseModel):
    """
    Notification event sent to Telegram/Slack.

    Fire-and-forget alerts (not persisted in database).
    """

    alert_id: str = Field(default_factory=lambda: str(uuid4()), description="UUID v4")
    severity: AlertSeverity = Field(..., description="Alert priority level")
    title: str = Field(..., min_length=1, max_length=100, description="Short alert title")
    body: str = Field(..., min_length=1, max_length=1000, description="Detailed alert message")
    context: dict[str, Any] = Field(
        default_factory=dict, description="Additional structured data (JSON-serializable)"
    )
    channel: AlertChannel = Field(..., description="Notification channel")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow, description="When alert was created"
    )
    sent_at: Optional[datetime] = Field(None, description="When alert was successfully sent")
    sent_status: bool = Field(default=False, description="Whether alert was sent successfully")
    error_message: Optional[str] = Field(None, description="Error details if sending failed")

    @model_validator(mode="after")
    def validate_sent_at(self) -> "Alert":
        """Validate sent_at is null when sent_status is False."""
        if not self.sent_status and self.sent_at is not None:
            raise ValueError("sent_at must be null when sent_status is False")
        if self.sent_status and self.sent_at is None:
            raise ValueError("sent_at must be non-null when sent_status is True")
        return self

    class Config:
        """Pydantic configuration."""

        json_encoders = {datetime: lambda v: v.isoformat()}


class IdempotencyKey(BaseModel):
    """
    Processed signal ID to prevent duplicate execution.

    Stored in SQLite with PRIMARY KEY on `key`.
    """

    key: str = Field(..., description="signal_id from TradingSignal")
    status: IdempotencyStatus = Field(..., description="Processing status")
    timestamp: datetime = Field(..., description="When key was inserted")
    error_message: Optional[str] = Field(None, description="Error details if status=FAILED")

    class Config:
        """Pydantic configuration."""

        json_encoders = {datetime: lambda v: v.isoformat()}


class OffsetCheckpoint(BaseModel):
    """
    Consumer's last processed position in JSONL queue.

    Updated atomically after each successfully processed signal.
    """

    offset: int = Field(default=0, ge=0, description="Line number (0-indexed) of last processed signal")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow, description="When offset was last updated"
    )

    class Config:
        """Pydantic configuration."""

        json_encoders = {datetime: lambda v: v.isoformat()}


# ============================================================================
# Helper Functions
# ============================================================================


def generate_signal_id(strategy: str) -> str:
    """
    Generate unique signal ID with format: TV-{YYYYMMDDHHMMSS}-{strategy_id}-{random4}.

    Args:
        strategy: Strategy name from TradingView (used to generate strategy_id slug)

    Returns:
        Unique signal ID matching regex: ^TV-\\d{14}-\\w+-\\w{4}$

    Example:
        >>> generate_signal_id("Smart Money Concepts [LuxAlgo]")
        'TV-20260116123010-smc_luxalgo-a3f2'
    """
    timestamp_part = datetime.utcnow().strftime("%Y%m%d%H%M%S")

    # Generate strategy_id slug from strategy name
    strategy_slug = (
        strategy.lower()
        .replace(" ", "_")
        .replace("[", "")
        .replace("]", "")
        .replace("-", "_")[:20]
    )
    # Remove non-word characters
    strategy_slug = "".join(c for c in strategy_slug if c.isalnum() or c == "_")

    # Generate random 4-character suffix
    random_suffix = "".join(random.choices(string.ascii_lowercase + string.digits, k=4))

    return f"TV-{timestamp_part}-{strategy_slug}-{random_suffix}"


def generate_client_order_id(signal_id: str, venue: Venue, leg: Leg, attempt: int) -> str:
    """
    Generate deterministic client_order_id.

    Format: {signal_id}:{venue}:{leg}:{attempt}

    Args:
        signal_id: Unique signal identifier from TradingSignal
        venue: Exchange name (BINANCE/HYPERLIQUID/MOCK)
        leg: Order purpose (ENTRY/EXIT)
        attempt: Retry attempt number (1-indexed)

    Returns:
        Deterministic client_order_id matching regex pattern

    Raises:
        ValueError: If attempt < 1

    Example:
        >>> generate_client_order_id("TV-20260116123010-smc_luxalgo-a3f2", Venue.MOCK, Leg.ENTRY, 1)
        'TV-20260116123010-smc_luxalgo-a3f2:MOCK:ENTRY:1'
    """
    if attempt < 1:
        raise ValueError(f"attempt must be >= 1, got {attempt}")

    return f"{signal_id}:{venue.value}:{leg.value}:{attempt}"


def validate_webhook_secret(secret: str) -> bool:
    """
    Validate webhook secret against environment variable WEBHOOK_SECRET.

    Args:
        secret: Secret from TradingView webhook request

    Returns:
        True if secret matches WEBHOOK_SECRET environment variable, False otherwise

    Raises:
        RuntimeError: If WEBHOOK_SECRET environment variable is not set

    Example:
        >>> os.environ["WEBHOOK_SECRET"] = "test_secret"
        >>> validate_webhook_secret("test_secret")
        True
        >>> validate_webhook_secret("wrong_secret")
        False
    """
    expected_secret = os.environ.get("WEBHOOK_SECRET")
    if not expected_secret:
        raise RuntimeError("WEBHOOK_SECRET environment variable is not set")

    # Use constant-time comparison to prevent timing attacks
    return secret == expected_secret


def derive_order_side(signal_side: Side, leg: Leg) -> OrderSide:
    """
    Derive exchange order side from signal side and leg.

    Args:
        signal_side: Trade direction from signal (LONG/SHORT)
        leg: Order purpose (ENTRY/EXIT)

    Returns:
        Order side for exchange (BUY/SELL)

    Logic:
        - LONG + ENTRY = BUY (enter long position)
        - LONG + EXIT = SELL (exit long position)
        - SHORT + ENTRY = SELL (enter short position)
        - SHORT + EXIT = BUY (exit short position / cover short)

    Example:
        >>> derive_order_side(Side.LONG, Leg.ENTRY)
        <OrderSide.BUY: 'BUY'>
        >>> derive_order_side(Side.SHORT, Leg.EXIT)
        <OrderSide.BUY: 'BUY'>
    """
    if signal_side == Side.LONG and leg == Leg.ENTRY:
        return OrderSide.BUY
    elif signal_side == Side.LONG and leg == Leg.EXIT:
        return OrderSide.SELL
    elif signal_side == Side.SHORT and leg == Leg.ENTRY:
        return OrderSide.SELL
    elif signal_side == Side.SHORT and leg == Leg.EXIT:
        return OrderSide.BUY
    else:
        raise ValueError(f"Invalid combination: signal_side={signal_side}, leg={leg}")
