# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Flask webhook server for receiving TradingView signals.

This module implements the HTTPS webhook endpoint that validates incoming
TradingView alerts and durably appends them to the JSONL queue.
"""

import logging
from datetime import datetime
from typing import Any, Optional

from flask import Flask, Request, jsonify, request
from pydantic import ValidationError

from trading_bot.config_manager.settings import Settings, get_settings
from trading_bot.schemas import (
    TradingSignal,
    TradingSignalRequest,
    generate_signal_id,
    validate_webhook_secret,
)
from trading_bot.storage.jsonl_queue import append_jsonl

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def create_app(config: Optional[dict[str, Any]] = None) -> Flask:
    """
    Create and configure the Flask application.

    Args:
        config: Optional configuration dictionary (for testing)

    Returns:
        Configured Flask application

    Example:
        >>> app = create_app()
        >>> client = app.test_client()
        >>> response = client.get("/health")
        >>> assert response.status_code == 200
    """
    app = Flask(__name__)

    # Load settings
    settings = get_settings()

    # Apply optional config overrides (for testing)
    if config:
        app.config.update(config)

    @app.route("/health", methods=["GET"])
    def health_check():
        """
        Health check endpoint for systemd monitoring.

        Returns:
            JSON response with status and timestamp

        Example:
            GET /health
            Response: {"status": "healthy", "timestamp": "2026-01-16T12:30:10.123456"}
        """
        return jsonify({"status": "healthy", "timestamp": datetime.utcnow().isoformat()})

    @app.route("/webhook/tradingview", methods=["POST"])
    def receive_tradingview_signal():
        """
        Receive and process TradingView trading signal.

        Validates secret, generates signal_id, and appends to JSONL queue.

        Request Body (JSON):
            {
                "secret": "your_webhook_secret",
                "strategy": "Smart Money Concepts [LuxAlgo]",
                "side": "LONG",
                "symbol": "BTCUSDT",
                "price": 90750.0,
                "timeframe": "15m"
            }

        Returns:
            200: {"signal_id": "TV-20260116123010-smc_luxalgo-a3f2", "status": "queued"}
            400: {"error": "Validation error message"}
            401: {"error": "Invalid webhook secret"}
            500: {"error": "Internal server error"}
        """
        try:
            # Parse request JSON
            payload = request.get_json(force=True)

            # Validate request payload with Pydantic
            try:
                signal_request = TradingSignalRequest(**payload)
            except ValidationError as e:
                logger.warning(f"Invalid request payload: {e}")
                return jsonify({"error": f"Validation error: {e}"}), 400

            # Validate webhook secret
            if not validate_webhook_secret(signal_request.secret):
                logger.warning(
                    f"Invalid webhook secret attempt from IP: {request.remote_addr}"
                )
                # TODO: Implement rate-limited alerting for invalid secret attempts
                # from trading_bot.alerts.router import AlertRouter
                # from trading_bot.schemas import Alert, AlertSeverity, AlertChannel
                # alert_router = AlertRouter(settings)
                # alert = Alert(
                #     severity=AlertSeverity.WARNING,
                #     title="Invalid Webhook Secret",
                #     message=f"Invalid secret attempt from IP: {request.remote_addr}",
                #     context={"ip": request.remote_addr, "payload": payload},
                #     timestamp=datetime.utcnow(),
                #     channel=AlertChannel.TELEGRAM,
                # )
                # alert_router.send(alert)
                return jsonify({"error": "Invalid webhook secret"}), 401

            # Generate unique signal_id
            signal_id = generate_signal_id(signal_request.strategy)

            # Create TradingSignal (without secret field)
            signal = TradingSignal(
                signal_id=signal_id,
                strategy=signal_request.strategy,
                side=signal_request.side,
                symbol=signal_request.symbol,
                price=signal_request.price,
                timeframe=signal_request.timeframe,
                timestamp=datetime.utcnow(),
            )

            # Append to JSONL queue with atomic write + fsync
            append_jsonl(settings.queue_path, signal.model_dump(mode="json"))

            # Log structured event (signal_received)
            log_signal_received_event(signal, settings)

            logger.info(
                f"Signal queued: {signal_id} ({signal.side} {signal.symbol} @ {signal.price})"
            )

            return (
                jsonify({"signal_id": signal_id, "status": "queued", "timestamp": signal.timestamp.isoformat()}),
                200,
            )

        except Exception as e:
            logger.error(f"Failed to process webhook: {e}", exc_info=True)
            return jsonify({"error": "Internal server error"}), 500

    @app.errorhandler(404)
    def not_found(error):
        """Handle 404 errors."""
        return jsonify({"error": "Endpoint not found"}), 404

    @app.errorhandler(405)
    def method_not_allowed(error):
        """Handle 405 errors."""
        return jsonify({"error": "Method not allowed"}), 405

    @app.errorhandler(500)
    def internal_error(error):
        """Handle 500 errors."""
        logger.error(f"Internal server error: {error}", exc_info=True)
        return jsonify({"error": "Internal server error"}), 500

    return app


def log_signal_received_event(signal: TradingSignal, settings: Settings) -> None:
    """
    Log structured signal_received event to event log.

    Args:
        signal: Trading signal that was received
        settings: Application settings

    Example:
        >>> signal = TradingSignal(...)
        >>> settings = get_settings()
        >>> log_signal_received_event(signal, settings)
    """
    event = {
        "event_type": "signal_received",
        "timestamp": datetime.utcnow().isoformat(),
        "signal_id": signal.signal_id,
        "strategy": signal.strategy,
        "side": signal.side.value,
        "symbol": signal.symbol,
        "price": str(signal.price),
        "timeframe": signal.timeframe,
    }

    try:
        append_jsonl(settings.event_log_path, event)
    except Exception as e:
        logger.error(f"Failed to log signal_received event: {e}", exc_info=True)


if __name__ == "__main__":
    # Development server (DO NOT USE IN PRODUCTION)
    # Use Gunicorn via wsgi.py for production deployment
    app = create_app()
    app.run(host="0.0.0.0", port=5000, debug=False)
