# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
WSGI entrypoint for Gunicorn production deployment.

This module creates the Flask app instance that Gunicorn will serve.
"""

from trading_bot.tradingview_webhook_server import create_app

# Create Flask app instance
app = create_app()

if __name__ == "__main__":
    # This should never be called directly - use Gunicorn
    print("ERROR: Do not run wsgi.py directly. Use Gunicorn:")
    print("  gunicorn trading_bot.wsgi:app --bind 0.0.0.0:5000 --workers 4")
