#!/usr/bin/env python3
"""
Strategy Discovery Scheduler
==============================
Runs the discovery engine on a weekly schedule.
Also generates a human-readable weekly report.

Schedule:
  - Every Sunday 02:00 UTC  — full discovery run (all 26 strategies, 4h data)
  - Every Sunday 03:30 UTC  — 15m timeframe discovery run
  - Daily 06:00 UTC         — re-score existing shortlist (prices may have changed)

Run as a daemon: python3 scripts/strategy_discovery_scheduler.py --daemon
Or trigger once: python3 scripts/strategy_discovery_scheduler.py --run-now
"""
import os, sys, json, logging, argparse
import schedule, time
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path('/home/ubuntu/tradingview_webhook_bot')
REPORT_DIR   = PROJECT_ROOT / 'storage' / 'reports' / 'strategy_discovery'
sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s %(levelname)s %(message)s',
    handlers=[
        logging.FileHandler(str(PROJECT_ROOT / 'logs' / 'strategy_discovery.log')),
        logging.StreamHandler(sys.stdout),
    ]
)
log = logging.getLogger('scheduler')


def weekly_4h_run():
    log.info('=== Weekly 4H Discovery Run Starting ===')
    try:
        from scripts.strategy_discovery_engine import run_discovery
        results = run_discovery(timeframes=('4h',))
        log.info(f'4H run complete: {len(results)} passed')
    except Exception as e:
        log.error(f'4H run failed: {e}', exc_info=True)


def weekly_15m_run():
    log.info('=== Weekly 15m Discovery Run Starting ===')
    try:
        from scripts.strategy_discovery_engine import run_discovery
        results = run_discovery(timeframes=('15m',))
        log.info(f'15m run complete: {len(results)} passed')
    except Exception as e:
        log.error(f'15m run failed: {e}', exc_info=True)


def daily_rescore():
    """Re-rank existing shortlist — no new backtests, just re-read latest results"""
    log.info('Daily shortlist re-score...')
    shortlist = REPORT_DIR / 'auto_shortlist.csv'
    if not shortlist.exists():
        log.info('No shortlist yet — skipping rescore')
        return
    try:
        import pandas as pd
        df = pd.read_csv(shortlist)
        df.sort_values(['kelly_sharpe', 'kelly_roi_annual'], ascending=False, inplace=True)
        df.to_csv(shortlist, index=False)

        # Generate daily summary
        top5 = df.head(5)
        summary_path = REPORT_DIR / f'daily_top5_{datetime.now(timezone.utc).strftime("%Y%m%d")}.txt'
        lines = [f'Daily Strategy Top-5 — {datetime.now(timezone.utc).strftime("%Y-%m-%d")}',
                 '='*60]
        for i, (_, row) in enumerate(top5.iterrows(), 1):
            lines.append(f'{i}. {row["strategy"]} / {row["symbol"]} {row["timeframe"]}')
            lines.append(f'   Sharpe={row["kelly_sharpe"]}  ROI={row["kelly_roi_annual"]}%/yr  DD={row["kelly_dd"]}%  PF={row["kelly_pf"]}')
        summary_path.write_text('\n'.join(lines))
        log.info(f'Daily top-5 saved: {summary_path}')
    except Exception as e:
        log.error(f'Rescore failed: {e}')


def generate_weekly_report():
    """Human-readable weekly markdown report"""
    shortlist = REPORT_DIR / 'auto_shortlist.csv'
    if not shortlist.exists():
        return
    try:
        import pandas as pd
        df  = pd.read_csv(shortlist).head(20)
        now = datetime.now(timezone.utc)
        report_path = REPORT_DIR / f'weekly_report_{now.strftime("%Y%m%d")}.md'
        lines = [
            f'# Strategy Discovery Weekly Report — {now.strftime("%Y-%m-%d")}',
            f'> Auto-generated by strategy_discovery_engine | {now.isoformat()}',
            '',
            '## Top Strategies (Kelly-Approved, DD < 20%)',
            '',
            '| # | Strategy | Symbol | TF | Annual ROI% | Sharpe | PF | WR% | Kelly DD% | Fixed DD% | DD Saved | Trades |',
            '|---|---|---|---|---|---|---|---|---|---|---|---|',
        ]
        for i, (_, row) in enumerate(df.iterrows(), 1):
            lines.append(f'| {i} | {row["strategy"]} | {row["symbol"]} | {row["timeframe"]} | '
                         f'{row["kelly_roi_annual"]}% | {row["kelly_sharpe"]} | {row["kelly_pf"]} | '
                         f'{row["kelly_wr"]}% | {row["kelly_dd"]}% | {row["fixed_dd"]}% | '
                         f'+{row["dd_saved"]}pp | {row["kelly_trades"]} |')
        lines += [
            '',
            '## What These Numbers Mean',
            '',
            '- **Sharpe > 0.35**: Risk-adjusted returns are positive and consistent',
            '- **PF > 1.25**: For every $1 lost, $1.25+ is made',
            '- **Kelly DD < -20%**: Maximum drawdown is controlled by dynamic position sizing',
            '- **Fixed DD**: What the drawdown WOULD be without Kelly (original issue)',
            '- **DD Saved**: How many percentage points Kelly saved vs fixed sizing',
            '',
            '## Promotion Criteria (to paper window)',
            '',
            '1. Strategy must appear in this shortlist for 2+ consecutive weekly runs',
            '2. DSR validation (deflated Sharpe — corrects for multiple testing)',
            '3. PBO/CSCV check (overfit probability)',
            '4. Sainath + Harsh manual review',
            '5. 7-day isolated paper window before any capital allocation',
            '',
            '## Web Discovery This Week',
        ]
        # Add latest web discovery if exists
        web_files = sorted(REPORT_DIR.glob('web_discovery_*.json'), reverse=True)
        if web_files:
            try:
                web = json.loads(web_files[0].read_text())
                lines.append(f'- GitHub repos found: {len(web.get("github", []))}')
                lines.append(f'- ArXiv papers found: {len(web.get("arxiv", []))}')
                lines.append(f'- Reddit posts found: {len(web.get("reddit", []))}')
                if web.get('arxiv'):
                    lines.append('')
                    lines.append('### Recent Quant Papers (ArXiv):')
                    for p in web['arxiv'][:3]:
                        lines.append(f'- **{p["title"][:80]}** ({p["date"]})')
                        lines.append(f'  {p["summary"][:150]}...')
            except Exception: pass

        lines += ['', f'*Generated: {now.isoformat()} | Do not edit manually*']
        report_path.write_text('\n'.join(lines))
        log.info(f'Weekly report saved: {report_path}')
    except Exception as e:
        log.error(f'Report generation failed: {e}')


def run_full_cycle():
    """Full cycle: discovery + report"""
    weekly_4h_run()
    generate_weekly_report()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--daemon', action='store_true', help='Run as background scheduler daemon')
    ap.add_argument('--run-now', action='store_true', help='Trigger one full run immediately')
    ap.add_argument('--quick', action='store_true', help='Quick test (first 5 strategies only)')
    args = ap.parse_args()

    if args.run_now or args.quick:
        if args.quick:
            log.info('Quick run mode (first 10 strategies)')
            from scripts.strategy_discovery_engine import run_discovery, BUILTIN_STRATEGIES
            quick_strats = dict(list(BUILTIN_STRATEGIES.items())[:10])
            from scripts.strategy_discovery_engine import run_discovery
            import scripts.strategy_discovery_engine as eng
            orig = eng.BUILTIN_STRATEGIES.copy()
            eng.BUILTIN_STRATEGIES = quick_strats
            run_discovery(timeframes=('4h',))
            eng.BUILTIN_STRATEGIES = orig
        else:
            run_full_cycle()
        return

    if args.daemon:
        log.info('Starting scheduler daemon...')
        log.info('Schedule: Sunday 02:00 UTC (4H), Sunday 03:30 UTC (15m), Daily 06:00 UTC (rescore)')

        schedule.every().sunday.at('02:00').do(run_full_cycle)
        schedule.every().sunday.at('03:30').do(weekly_15m_run)
        schedule.every().day.at('06:00').do(daily_rescore)

        log.info('Scheduler running. Next jobs:')
        for job in schedule.jobs:
            log.info(f'  {job}')

        while True:
            schedule.run_pending()
            time.sleep(60)
    else:
        ap.print_help()


if __name__ == '__main__':
    main()
