# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Alert router for sending notifications to Telegram/Slack.

This module handles alert dispatch with rate limiting and error handling.
"""

import logging
import time
from collections import deque
from datetime import datetime
from typing import Any, Optional

import requests

from trading_bot.alerts.templates import format_alert
from trading_bot.config_manager.settings import get_settings
from trading_bot.schemas import Alert, AlertChannel, AlertSeverity
from trading_bot.storage.jsonl_queue import append_jsonl

logger = logging.getLogger(__name__)


class AlertRouter:
    """
    Alert router with rate limiting.

    Sends alerts to configured channels (Telegram/Slack) with rate limiting
    to prevent notification spam.
    """

    def __init__(self, max_alerts_per_minute: int = 10):
        """
        Initialize alert router.

        Args:
            max_alerts_per_minute: Maximum alerts per minute (default: 10)

        Example:
            >>> router = AlertRouter(max_alerts_per_minute=10)
        """
        self.max_alerts_per_minute = max_alerts_per_minute
        self._alert_timestamps: deque[float] = deque(maxlen=max_alerts_per_minute)
        self.settings = get_settings()

    def send(
        self,
        severity: AlertSeverity,
        title: str,
        body: str,
        channel: AlertChannel = AlertChannel.TELEGRAM,
        **context: Any,
    ) -> bool:
        """
        Send an alert to notification channel.

        Args:
            severity: Alert severity level
            title: Short alert title (1-100 chars)
            body: Detailed alert message (1-1000 chars)
            channel: Notification channel (default: TELEGRAM)
            **context: Additional context as keyword arguments

        Returns:
            True if alert was sent successfully, False otherwise

        Example:
            >>> router = AlertRouter()
            >>> router.send(
            ...     AlertSeverity.CRITICAL,
            ...     "Position Drift",
            ...     "Drift detected: 0.5 BTC",
            ...     symbol="BTCUSDT",
            ...     drift="0.5"
            ... )
        """
        # Check rate limit
        if not self._check_rate_limit():
            logger.warning(
                f"Alert rate limit exceeded ({self.max_alerts_per_minute}/minute). "
                "Dropping alert."
            )
            # TODO: Batch dropped alerts into summary message
            return False

        # Format message
        message = format_alert(severity, title, body, context)

        # Create alert record
        alert = Alert(
            severity=severity,
            title=title,
            body=body,
            context=context,
            channel=channel,
        )

        # Send to channel
        try:
            if channel == AlertChannel.TELEGRAM:
                success = self._send_telegram(message)
            elif channel == AlertChannel.SLACK:
                success = self._send_slack(message)
            else:
                logger.error(f"Unsupported alert channel: {channel}")
                success = False

            # Update alert status
            if success:
                alert.sent_at = datetime.utcnow()
                alert.sent_status = True
                logger.info(f"Alert sent: {title}")
            else:
                alert.error_message = "Failed to send alert"
                logger.error(f"Alert failed: {title}")

            # Log alert event
            self._log_alert_event(alert)

            return success

        except Exception as e:
            logger.error(f"Alert error: {e}", exc_info=True)
            alert.error_message = str(e)
            self._log_alert_event(alert)
            return False

    def _check_rate_limit(self) -> bool:
        """Check if rate limit allows sending another alert."""
        now = time.time()

        # Remove timestamps older than 1 minute
        cutoff = now - 60
        while self._alert_timestamps and self._alert_timestamps[0] < cutoff:
            self._alert_timestamps.popleft()

        # Check if under limit
        if len(self._alert_timestamps) >= self.max_alerts_per_minute:
            return False

        # Add current timestamp
        self._alert_timestamps.append(now)
        return True

    def _send_telegram(self, message: str) -> bool:
        """Send alert to Telegram."""
        try:
            url = f"https://api.telegram.org/bot{self.settings.telegram_token}/sendMessage"
            payload = {
                "chat_id": self.settings.telegram_chat_id,
                "text": message,
                "parse_mode": "Markdown",
            }

            response = requests.post(url, json=payload, timeout=10)
            response.raise_for_status()

            logger.debug("Telegram alert sent successfully")
            return True

        except Exception as e:
            logger.error(f"Telegram send failed: {e}", exc_info=True)
            return False

    def _send_slack(self, message: str) -> bool:
        """Send alert to Slack."""
        # TODO: Implement Slack integration
        logger.warning("Slack integration not implemented yet")
        return False

    def _log_alert_event(self, alert: Alert) -> None:
        """Log alert_sent event."""
        event = {
            "event_type": "alert_sent",
            "timestamp": datetime.utcnow().isoformat(),
            "alert_id": alert.alert_id,
            "severity": alert.severity.value,
            "title": alert.title,
            "body": alert.body,
            "context": alert.context,
            "channel": alert.channel.value,
            "sent_status": alert.sent_status,
            "error_message": alert.error_message,
        }
        try:
            append_jsonl(self.settings.event_log_path, event)
        except Exception as e:
            logger.error(f"Failed to log alert_sent event: {e}")
