# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Alert rules for triggering notifications.

This module defines conditions for sending alerts based on system events.
"""

import logging
from decimal import Decimal

logger = logging.getLogger(__name__)


def invalid_secret_threshold(count: int, window_seconds: int = 60) -> bool:
    """
    Check if invalid secret attempts exceed threshold.

    Args:
        count: Number of invalid attempts
        window_seconds: Time window (default: 60 seconds)

    Returns:
        True if threshold exceeded

    Example:
        >>> if invalid_secret_threshold(count=5, window_seconds=60):
        ...     # Send alert
        ...     pass
    """
    threshold = 3  # TODO: Make configurable
    exceeded = count >= threshold

    if exceeded:
        logger.warning(
            f"Invalid secret threshold exceeded: {count} attempts in {window_seconds}s"
        )

    return exceeded


def drift_threshold(drift: Decimal, tolerance: Decimal) -> bool:
    """
    Check if position drift exceeds tolerance.

    Args:
        drift: Absolute drift amount
        tolerance: Tolerance threshold

    Returns:
        True if drift exceeds tolerance

    Example:
        >>> if drift_threshold(Decimal("0.5"), Decimal("0.1")):
        ...     # Send alert
        ...     pass
    """
    exceeded = drift > tolerance

    if exceeded:
        logger.warning(f"Drift threshold exceeded: drift={drift}, tolerance={tolerance}")

    return exceeded


def dead_letter_alert() -> bool:
    """
    Always alert on dead letter queue events.

    Returns:
        True (always alert)

    Example:
        >>> if dead_letter_alert():
        ...     # Send alert
        ...     pass
    """
    return True


def reconciliation_failure_alert() -> bool:
    """
    Always alert on reconciliation failures.

    Returns:
        True (always alert)

    Example:
        >>> if reconciliation_failure_alert():
        ...     # Send alert
        ...     pass
    """
    return True
