# GENERATED BY CLAUDE — REVIEW BEFORE MERGE
"""
Alert message templates for Telegram/Slack.

This module formats alert messages with context for human-readable notifications.
"""

import logging
from typing import Any

from trading_bot.schemas import AlertSeverity

logger = logging.getLogger(__name__)


def format_alert(
    severity: AlertSeverity, title: str, body: str, context: dict[str, Any]
) -> str:
    """
    Format alert message for notification channel.

    Args:
        severity: Alert severity level
        title: Short alert title
        body: Detailed alert message
        context: Additional structured data

    Returns:
        Formatted message string

    Example:
        >>> msg = format_alert(
        ...     AlertSeverity.CRITICAL,
        ...     "Position Drift Detected",
        ...     "Derived position does not match exchange",
        ...     {"drift": "0.5", "symbol": "BTCUSDT"}
        ... )
        >>> print(msg)
    """
    # Emoji for severity
    severity_emoji = {
        AlertSeverity.INFO: "ℹ️",
        AlertSeverity.WARNING: "⚠️",
        AlertSeverity.CRITICAL: "🚨",
    }

    emoji = severity_emoji.get(severity, "📢")

    # Format message
    message = f"{emoji} **{severity.value}: {title}**\n\n{body}"

    # Add context if provided
    if context:
        message += "\n\n**Context:**"
        for key, value in context.items():
            message += f"\n• {key}: {value}"

    return message
